version: '3.8'

services:
  chachet:
    image: cachethq/docker:latest
    container_name: cachet
    restart: always
    ports:
      - "80:8000"
    environment:
      - APP_KEY=${APP_KEY}              
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_DRIVER=mysql
      - DB_HOST=${DB_HOST}    
      - DB_DATABASE=cachet
      - DB_USERNAME=admin
      - DB_PASSWORD=yagHxgDb0GCwf89EXdTkm4HqGTJmkNHp
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - cachet-net

  redis:
    image: redis:alpine
    container_name: cachet-redis
    restart: always
    networks:
      - cachet-net

networks:
  cachet-net:
    driver: bridge